export const projects = [
  {
    name: "QuiverAI",
    description: "Product engineer",
    year: "2026–Present",
    age: 16,
    href: "https://quiver.ai",
    logo: "/svg/quiver.svg",
    tone: "quiver",
  },
  {
    name: "HackSpain",
    description: "Co-founder",
    year: "2026–Present",
    age: 16,
    href: "https://hackspain.com",
    logo: "/hackspain-icon.png",
    tone: "hackspain",
  },
  {
    name: "Ladda",
    description: "Fashion e-commerce",
    year: "2026",
    age: 16,
    tone: "ladda",
  },
  {
    name: "Avalio",
    description: "Investing simulator",
    year: "2025–26",
    age: 15,
    href: "https://avalio.markets",
    tone: "avalio",
  },
  {
    name: "fellows.best",
    description: "Tech fellowships",
    year: "2024–26",
    age: 14,
    href: "https://fellows.best/",
    tone: "fellows",
  },
  {
    name: "Syntara AI",
    description: "AI reasoning",
    year: "2024",
    age: 14,
    href: "https://github.com/samuelcorsan/syntara-ai",
    tone: "syntara",
  },
  {
    name: "Freelance",
    description: "Web development",
    year: "2023–24",
    age: 13,
    tone: "freelance",
  },
  {
    name: "Caotic Robbers",
    description: "Roblox game",
    year: "2020–22",
    age: 9,
    href: "https://www.youtube.com/watch?v=loQrByYbWZw",
    tone: "caotic",
  },
];
