import Header from "@/components/header";
import Footer from "@/components/footer";
import Image from "next/image";
import Code from "@/components/Code";

export default function WhyWeBuiltShipFreePost() {
  return (
    <>
      <Header showHomeLink={true} />
      <div className="max-w-4xl mx-auto px-4 py-8">
        <h1 className="text-[2.5rem] font-serif tracking-tight text-primary">
          Vibe code, big risks: how to fix common security holes
        </h1>
        <p className="text-sm text-foreground">Jun 07, 2025</p>

        <h2 className="text-base mt-4 text-gray-300">
          Vibe coding (relying on ai tools to generate code snippets,
          components, or entire modules) can dramatically speed up development.
          but it also introduces subtle security risks. ai-generated code often
          lacks context around your app's specific security requirements,
          leading to gaps that bad actors can exploit. in this post, we'll
          explore the most common vulnerabilities introduced by ai-assisted
          development, demonstrate examples in react/next.js, and show you
          exactly how to patch them (these fixes can be applied to any
          framework).
        </h2>

        <div className="mt-6 prose prose-sm max-w-none prose-headings:text-primary prose-p:text-gray-300 prose-a:text-white prose-a:underline prose-a:decoration-1 prose-a:underline-offset-4 prose-a:font-medium prose-a:mx-1 prose-li:text-foreground prose-ol:text-foreground prose-ul:text-foreground">
          <Image
            src="/images/vibe-coding-bugs.png"
            alt="ShipFree Growth Chart"
            width={1000}
            height={1000}
            className="w-full rounded-lg shadow-lg !mb-2"
          />
          <a
            href="https://x.com/icanvardar/status/1930293312235155842"
            target="_blank"
            rel="noopener noreferrer"
            className="text-md !text-gray-400 !no-underline hover:!underline"
          >
            Photo by Can Vardar
          </a>

          <p>by the end, you'll understand:</p>
          <ul className="list-disc pl-5">
            <li className="!text-gray-300">
              why ai-generated code can be insecure
            </li>
            <li className="!text-gray-300">
              the top security holes to watch for
            </li>
            <li className="!text-gray-300">
              concrete react/next.js examples of "bad" ai code
            </li>
            <li className="!text-gray-300">how to fix them in</li>
          </ul>
          <p>let's dive in.</p>

          <h2>Why ai-generated code can be risky</h2>
          <p>
            AI coding assistants (cursor, lovable...) excel at filling in
            boilerplate and scaffolding. but they don't automatically think
            about:
          </p>
          <ul className="list-disc pl-5">
            <li className="!text-gray-300">
              the performance and security problems that their generated code
              can cause
            </li>
            <li className="!text-gray-300">
              treating your application as if you were not going to release it
              to production
            </li>
            <li className="!text-gray-300">
              leaving your endpoints free of rate limits or your keys exposed
            </li>
            <li className="!text-gray-300">
              organizational policies or compliance (gdpr, hipaa, etc.)
            </li>
          </ul>
          <p>
            Let's look at common examples that developers don't usually care
            about that expose their apps, as well as their solutions. We will
            also add common generations of code that can make your app's
            performance worse.
          </p>

          <h2 className="text-2xl">1. Lack of rate limiting</h2>

          <p className="mb-6">
            AI code assistants will generate your endpoints but won't add rate
            limiting by default, leaving your APIs vulnerable to abuse. Let's
            look at examples of how to properly secure these endpoints.
          </p>

          <div className="space-y-8">
            <div>
              <div className="gap-2 mb-3">
                <h3 className="text-xl font-medium !text-red-400">
                  Vulnerable endpoint (AI-generated)
                </h3>
              </div>
              <p className="text-gray-300 mb-4">
                This is a typical endpoint generated by AI assistants like
                Cursor. It implements basic authentication functionality but
                lacks any protection against brute force attacks or DoS
                attempts. An attacker could make unlimited login attempts,
                potentially compromising user accounts or overloading your
                server.
              </p>
              <Code
                code={`// app/api/your-endpoint/route.ts
// nextjs endpoint but can be applied to any framework
export async function POST(request: Request) {
  // example user logic
  const userData = await request.json();
  const { username } = userData;

  // handler logic
  return Response.json({ username, status: 'success' })
}`}
                lang="typescript"
              />
            </div>

            <div>
              <div className="mb-3">
                <h3 className="text-xl font-medium !text-green-400">
                  Secure endpoint (with rate limiting)
                </h3>
              </div>
              <p className="text-gray-300 mb-4">
                Here's the same endpoint properly secured using Upstash Redis
                for rate limiting. We implement a sliding window rate limiter
                that allows 10 requests per minute per IP address. This modern
                approach is perfect for serverless environments and provides
                precise control over API access patterns. The sliding window
                mechanism is more accurate than traditional rate limiting and
                helps prevent request bursts at window boundaries.
              </p>
              <Code
                code={`// app/api/your-endpoint/route.ts
import { Ratelimit } from '@upstash/ratelimit'
import { Redis } from '@upstash/redis'
import requestIp from 'request-ip'

const redis = new Redis({
  url: process.env.UPSTASH_REDIS_REST_URL!,
  token: process.env.UPSTASH_REDIS_REST_TOKEN!,
})

// Create a sliding-window rate limiter (10 reqs/minute)
const rateLimiter = new Ratelimit({
  redis,
  limiter: Ratelimit.slidingWindow(10, '1m'),
})

export async function POST(request: Request) {
  const ip = requestIp.getClientIp(request) || 'anonymous'
  const { success } = await rateLimiter.limit(\`ip:\${ip}\`)
  const userData = await request.json();
  const { username } = userData;

  if (!success) {
    return NextResponse.json(
      { error: 'Too many requests' },
      { status: 429 }
    )
  }

  // handler logic
  return Response.json({ username, status: 'success' })
}`}
                lang="typescript"
              />
            </div>
          </div>

          <h2 className="text-2xl">2. Input validation / sanitization</h2>
          <p>To be continued...</p>
        </div>
      </div>
      <Footer />
    </>
  );
}
